# Generated by Django 3.1.7 on 2021-03-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0008_auto_20210309_0043'),
        ('host', '0002_auto_20210312_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredplayer',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='images/certificates'),
        ),
        migrations.AlterField(
            model_name='registeredplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team_leader.player'),
        ),
        migrations.AlterField(
            model_name='registeredteam',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team_leader.team'),
        ),
    ]
