# Generated by Django 3.1.7 on 2021-03-23 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('host', '0006_playerresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='judge_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Judge1', to='account.judgemodel'),
        ),
        migrations.AddField(
            model_name='event',
            name='judge_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Judge2', to='account.judgemodel'),
        ),
        migrations.AddField(
            model_name='event',
            name='judge_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Judge3', to='account.judgemodel'),
        ),
    ]
