# Generated by Django 3.1.7 on 2021-03-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_auto_20210323_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerresult',
            name='accuracy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playerresult',
            name='presentation',
            field=models.FloatField(default=0),
        ),
    ]
