# Generated by Django 3.1.7 on 2021-03-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0008_auto_20210323_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerresult',
            name='round',
            field=models.IntegerField(),
        ),
    ]
