# Generated by Django 3.1.7 on 2021-03-25 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0009_auto_20210323_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='outline',
            field=models.FileField(blank=True, null=True, upload_to='outlines/'),
        ),
    ]
