# Generated by Django 3.1.7 on 2021-03-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0010_event_outline'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_reg',
            field=models.BooleanField(default=True),
        ),
    ]
