# Generated by Django 3.1.7 on 2021-03-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0012_auto_20210327_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredteam',
            name='payment_done',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
