# Generated by Django 3.1.14 on 2023-05-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0016_auto_20210707_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='num_of_player',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=1),
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
