# Generated by Django 3.1.14 on 2023-05-08 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0017_auto_20230508_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='num_of_player',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3')], default=1),
        ),
    ]
