# Generated by Django 3.1.14 on 2023-05-08 23:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0020_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='max_age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='min_age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
