# Generated by Django 3.1.14 on 2023-05-10 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0016_auto_20230501_1745'),
        ('host', '0021_auto_20230508_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_done', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.category')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team_leader.player')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.subcategory')),
            ],
        ),
    ]
