# Generated by Django 3.1.14 on 2023-05-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0023_auto_20230510_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredmember',
            name='has_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeredmember',
            name='parent_member',
            field=models.ForeignKey(blank=True, limit_choices_to={models.BooleanField(default=False): False}, null=True, on_delete=django.db.models.deletion.CASCADE, to='host.registeredmember'),
        ),
    ]
