# Generated by Django 3.1.14 on 2023-05-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0024_auto_20230514_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredmember',
            name='parent_member',
            field=models.ForeignKey(blank=True, limit_choices_to={'has_parent': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submembers', to='host.registeredmember'),
        ),
    ]
