# Generated by Django 3.1.14 on 2023-05-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0016_auto_20230501_1745'),
        ('host', '0025_auto_20230514_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeredmember',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team_leader.team'),
        ),
        migrations.AlterField(
            model_name='registeredmember',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='team_leader.player'),
        ),
    ]
