# Generated by Django 3.1.14 on 2023-06-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0027_event_allow_manage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allow_payment',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
