# Generated by Django 3.1.14 on 2023-06-04 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0028_event_allow_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allow_manage',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='allow_reg',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
