version: "3.7"

services: 
  db:
    container_name: db_container
    image: mysql:5.7.33
    restart: unless-stopped
    env_file: 
      - .env
    volumes: 
      - dbdata:/var/lib/mysql
    ports: 
      - 33066:3306
  app:
    container_name: app_container
    restart: unless-stopped
    env_file: 
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes: 
      - ./app:/app
    ports: 
      - 8000:8000
    depends_on: 
      - db

volumes: 
  dbdata:
