services:
  taekwonsoftbd_db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - taekwonsoftbd_network
  taekwonsoftbd_app:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./app
      dockerfile: Dockerfile_PROD
    volumes:
      - assets:/assets
    depends_on:
      - taekwonsoftbd_db
    networks:
      - taekwonsoftbd_network
  taekwonsoftbd_proxy:
    restart: unless-stopped
    env_file:
      - .env
    build:
      context: ./proxy
      dockerfile: Dockerfile_PROD
    volumes:
      - assets:/assets
      - sslfiles:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    depends_on:
      - taekwonsoftbd_app
    networks:
      - taekwonsoftbd_network

volumes:
  dbdata:
  assets:
  sslfiles:


networks:
  taekwonsoftbd_network:
    driver: bridge
