# Generated by Django 3.1.7 on 2021-03-08 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50, null=True)),
                ('teamleader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teamleadermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=7)),
                ('dob', models.DateField()),
                ('country', models.CharField(max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/player')),
                ('teamleader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teamleadermodel')),
            ],
        ),
    ]
