# Generated by Django 3.1.7 on 2021-03-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='profile_picture',
            new_name='picture',
        ),
    ]
