# Generated by Django 3.1.7 on 2021-03-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0002_auto_20210308_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='district',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
