# Generated by Django 3.1.7 on 2021-03-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0004_auto_20210308_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='district',
            field=models.CharField(default='Noakhali', max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(default='default_boy.png', upload_to='images/player'),
        ),
    ]
