# Generated by Django 3.1.7 on 2021-03-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0005_auto_20210309_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(upload_to='images/player'),
        ),
    ]
