# Generated by Django 3.1.7 on 2021-03-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0006_auto_20210309_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='district',
            field=models.CharField(default='', max_length=50),
        ),
    ]
