# Generated by Django 3.1.7 on 2021-04-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0008_auto_20210309_0043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='date_of_birth',
            new_name='date_Of_Birth',
        ),
        migrations.RemoveField(
            model_name='player',
            name='district',
        ),
        migrations.AddField(
            model_name='player',
            name='dan_Certificate',
            field=models.ImageField(blank=True, null=True, upload_to='images/dan_certificates'),
        ),
        migrations.AddField(
            model_name='player',
            name='dan_Certificate_No',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='gMS_Licence_No',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='member_Type',
            field=models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('doctor', 'Doctor'), ('manager', 'Manager'), ('guardian', 'Guardian'), ('owner', 'Owner'), ('instructor', 'Instructor'), ('team_official', 'Team Official'), ('media', 'Media'), ('volunteer', 'Vaulenteer'), ('referee', 'Referee')], default='male', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='passport_or_ID_Card',
            field=models.ImageField(blank=True, null=True, upload_to='images/passport_or_nid'),
        ),
    ]
