# Generated by Django 3.1.7 on 2021-04-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0009_auto_20210417_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='district',
        ),
        migrations.AddField(
            model_name='team',
            name='club_Name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(default='images/profile_pics/bot_sq_KCCLFuN.png', upload_to='images/team_logo'),
        ),
    ]
