# Generated by Django 3.1.7 on 2021-04-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0010_auto_20210417_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_logo',
            field=models.ImageField(upload_to='images/team_logo'),
        ),
    ]
