# Generated by Django 3.1.7 on 2021-04-18 12:17

from django.db import migrations, models
import team_leader.models


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0013_auto_20210417_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(upload_to='images/player', validators=[team_leader.models.validate_player_image]),
        ),
    ]
