# Generated by Django 3.1.14 on 2023-05-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_leader', '0015_remove_player_member_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='passport_or_ID_Card',
            field=models.ImageField(default='', upload_to='images/passport_or_nid'),
            preserve_default=False,
        ),
    ]
