FROM python:3.9.2
ENV PYTHONUNBUFFERED 1

COPY ./requirements.txt ./requirements.txt

RUN pip install -r requirements.txt

RUN mkdir /app
COPY . /app
WORKDIR /app

RUN mkdir -p /assets/static
RUN mkdir -p /assets/media

RUN adduser user

RUN chown -R user:user /assets
RUN chmod -R 755 /assets

RUN chmod +x "entrypoint.sh"

USER user

CMD [ "sh", "entrypoint.sh" ]
