# Generated by Django 3.1.14 on 2023-05-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('10th_gup', '10th Gup'), ('9th_gup', '9th Gup'), ('8th_gup', '8th Gup'), ('7th_gup', '7th Gup'), ('6th_gup', '6th Gup'), ('5th_gup', '5th Gup'), ('4th_gup', '4th Gup'), ('3rd_gup', '3rd Gup'), ('2nd_gup', '2nd Gup'), ('1st_gup', '1st Gup'), ('4th_poom', '4th Poom'), ('3rd_poom', '3rd Poom'), ('2nd_poom', '2nd Poom'), ('1st_poom', '1st Poom'), ('9th_dan', '9th Dan'), ('8th_dan', '8th Dan'), ('7th_dan', '7th Dan'), ('6th_dan', '6th Dan'), ('5th_dan', '5th Dan'), ('4th_dan', '4th Dan'), ('3rd_dan', '3rd Dan'), ('2nd_dan', '2nd Dan'), ('1st_dan', '1st Dan')], default='black', max_length=12),
        ),
    ]
